["powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    exact = true
    clone.args = ["--depth", "1"]
    refreshPeriod = "168h"

[".zsh/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
    exact = true
    clone.args = ["--depth", "1"]
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    exact = true
    clone.args = ["--depth", "1"]
    refreshPeriod = "168h"

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    exact = true
    clone.args = ["--depth", "1"]
    refreshPeriod = "168h"

[".fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

{{ $fzfVersion := "0.56.3" -}}
[".fzf/bin/fzf"]
    type = "archive-file"
    url = "https://github.com/junegunn/fzf/releases/download/v{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-linux_{{ .chezmoi.arch }}.tar.gz"
    path = "fzf"

# [".nvim"]
#     type = "archive"
#     url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
#     executable = true

[".local/bin/mise"]
    type = "file"
    url = "https://mise.jdx.dev/mise-latest-linux-{{ .chezmoi.arch }}"
    executable = true

