["powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    clone.args = ["--depth 1"]

[".zsh/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
    clone.args = ["--depth 1"]

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    clone.args = ["--depth 1"]

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    clone.args = ["--depth 1"]
